# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

cluster = {
  "bank-1" => { :ip => "10.99.1.13", :cpus => 1, :mem => 512, :sources => './bank', :destination => 'bank', :bootstrap => './bank/bootstrap.sh' },
  "bank-2" => { :ip => "10.99.1.14", :cpus => 1, :mem => 512, :sources => './bank', :destination => 'bank', :bootstrap => './bank/bootstrap.sh' },
  "bank-3" => { :ip => "10.99.1.15", :cpus => 1, :mem => 512, :sources => './bank', :destination => 'bank', :bootstrap => './bank/bootstrap.sh' },
  "bank-4" => { :ip => "10.99.1.16", :cpus => 1, :mem => 512, :sources => './bank', :destination => 'bank', :bootstrap => './bank/bootstrap.sh' }
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
	  cfg.vm.box = "ubuntu/trusty32"
	  cfg.vm.provider :virtualbox do |vb, override|
		override.vm.network :private_network, ip: "#{info[:ip]}"
		override.vm.hostname = hostname
		vb.name = hostname
		vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "off", "--usb", "off"]
      end # end provider
		
		
	  cfg.vm.provision "file", source: "#{info[:sources]}", destination: "#{info[:destination]}"
		
	  cfg.vm.provision "shell", path: "#{info[:bootstrap]}"
	end # end config
  end # end cluster
end

